spring:
  data:
    rest:
      base-path: /api

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    show-sql: true
    generate-ddl: true
    database-platform: POSTGRES
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver

management:
  port: 7979
  security:
    enabled: false

flyway:
  enabled: true

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO

sba:
  adminPassword: ${SBA_SECURITY_PASSWORD:admin}
