spring:
  data:
    rest:
      base-path: /api

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    database-platform: POSTGRES
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

flyway:
  enabled: false

security:
  basic:
    enabled: true
  user:
    name: ${SBA_SECURITY_USER:admin}
    password: ${SBA_SECURITY_PASSWORD:admin}

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO