spring:
  data:
    rest:
      base-path: /api

  thymeleaf:
    cache: false

security:
  basic:
    enabled: true
  user:
    name: ${SBA_SECURITY_USER:admin}
    password: ${SBA_SECURITY_PASSWORD:admin}

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO