#
#
#
security:
  basic:
    enabled: false

flyway:
  enabled: false

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    show-sql: true
    generate-ddl: true
    database-platform: H2
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect

  datasource:
    driver-class-name: org.h2.Driver