#
#
#
security:
  basic:
    enabled: false

flyway:
  enabled: false

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    show-sql: true
    generate-ddl: true
    database-platform: H2
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect

  datasource:
    driver-class-name: org.h2.Driver
# we want to use github-login, so include profile here
  profiles:
    include: github

server:
    port: 8443
    ssl:
        key-store: classpath:keystore.p12
        key-store-type: PKCS12
        key-store-password: mypassword
        key-alias: tomcat