spring:
  data:
    rest:
      base-path: /api

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    show-sql: true
    generate-ddl: true
    database-platform: POSTGRES
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

management:
  port: 7979

flyway:
  enabled: true

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO

sba:
  adminPassword: ${SBA_SECURITY_PASSWORD:admin}